# Generated by Django 4.1.3 on 2023-03-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_alter_payment_payment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
