# Generated by Django 4.1.3 on 2023-03-15 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0092_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('sch_date', models.DateField()),
                ('sch_time', models.CharField(max_length=255)),
                ('d_name', models.CharField(max_length=255)),
                ('d_email', models.CharField(max_length=255)),
                ('items', models.CharField(default='', max_length=1000)),
                ('b_date', models.DateTimeField(auto_now_add=True)),
                ('doctors', models.ManyToManyField(to='home.doctor')),
                ('listof_patient', models.ManyToManyField(to='home.patient_list')),
                ('username', models.ForeignKey(db_column='username', default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
